import Head from "next/head";
import React, { useEffect } from 'react'
import Aos from 'aos';
import "aos/dist/aos.css";
import Icode from "/components/Icode";
import Image from 'next/image'
import Nv from "/components/Nv";
import Eshow from "/components/Eshow";
import styles from "/styles/Explore.module.css";
export default function Explore() {

  return (
    
      <>

<Head>
        <title>   
         Explore - Arrow Nap
          </title>
        <meta
          name="description"
          content="Arrow Nap| Arrow Nap is the knowledge-sharing community Of Developers."
        />
        <link rel="icon" href="favicon.ico" />
     

      </Head>
<div>
      <Nv p={"static"}  />
    </div>

    <><Eshow/></>
<div className={styles.block}>
  <h1 className={styles.bo}>  TRENDING<Image src="/trending.png" alt="T"  height={'40%'}  width={'40%'}  /></h1></div>

<Icode/>
      
    </>
  )
}

// import * as React from 'react';
// import { styled } from '@mui/material/styles';
// import AppBar from '@mui/material/AppBar';
// import Box from '@mui/material/Box';
// import CssBaseline from '@mui/material/CssBaseline';
// import Toolbar from '@mui/material/Toolbar';
// import Typography from '@mui/material/Typography';
// import IconButton from '@mui/material/IconButton';
// import Paper from '@mui/material/Paper';
// import Fab from '@mui/material/Fab';
// import List from '@mui/material/List';
// import ListItem from '@mui/material/ListItem';
// import ListItemAvatar from '@mui/material/ListItemAvatar';
// import ListItemText from '@mui/material/ListItemText';
// import ListSubheader from '@mui/material/ListSubheader';
// import Avatar from '@mui/material/Avatar';
// import MenuIcon from '@mui/icons-material/Menu';
// import AddIcon from '@mui/icons-material/Add';
// import SearchIcon from '@mui/icons-material/Search';
// import MoreIcon from '@mui/icons-material/MoreVert';

// const messages = [
//   {
//     id: 1,
//     primary: 'Brunch this week?',
//     secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
//     person: '/static/images/avatar/5.jpg',
//   },
//   {
//     id: 1,
//     primary: 'Birthday Gift',
//     secondary: `Do you have a suggestion for a good present for John on his work
//       anniversary. I am really confused & would love your thoughts on it.`,
//     person: '/static/images/avatar/1.jpg',
//   },
//   {
//     id: 1,
//     primary: 'Recipe to try',
//     secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
//     person: '/static/images/avatar/2.jpg',
//   },
//   {
//     id: 4,
//     primary: 'Yes!',
//     secondary: 'I have the tickets to the ReactConf for this year.',
//     person: '/static/images/avatar/3.jpg',
//   },
//   {
//     id: 5,
//     primary: "Doctor's Appointment",
//     secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
//     person: '/static/images/avatar/4.jpg',
//   },
//   {
//     id: 3,
//     primary: 'Discussion',
//     secondary: `Menus that are generated by the bottom app bar (such as a bottom
//       navigation drawer or overflow menu) open as bottom sheets at a higher elevation
//       than the bar.`,
//     person: '/static/images/avatar/5.jpg',
//   },
//   {
//     id: 3,
//     primary: 'Summer BBQ',
//     secondary: `Who wants to have a cookout this weekend? I just got some furniture
//       for my backyard and would love to fire up the grill.`,
//     person: '/static/images/avatar/1.jpg',
//   },
//   {
//     id: 3,
//     primary: 'Yes!',
//     secondary: 'I have the tickets to the ReactConf for this year.',
//     person: '/static/images/avatar/3.jpg',
//   },
//   {
//     id: 9,
//     primary: "Doctor's Appointment",
//     secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
//     person: '/static/images/avatar/4.jpg',
//   },
//   {
//     id: 10,
//     primary: 'Discussion',
//     secondary: `Menus that are generated by the bottom app bar (such as a bottom
//       navigation drawer or overflow menu) open as bottom sheets at a higher elevation
//       than the bar.`,
//     person: '/static/images/avatar/5.jpg',
//   },
//   {
//     id: 11,
//     primary: 'Summer BBQ',
//     secondary: `Who wants to have a cookout this weekend? I just got some furniture
//       for my backyard and would love to fire up the grill.`,
//     person: '/static/images/avatar/1.jpg',
//   },
//   {
//     id: 12,
//     primary: "Doctor's Appointment",
//     secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
//     person: '/static/images/avatar/4.jpg',
//   },
//   {
//     id: 13,
//     primary: 'Discussion',
//     secondary: `Menus that are generated by the bottom app bar (such as a bottom
//       navigation drawer or overflow menu) open as bottom sheets at a higher elevation
//       than the bar.`,
//     person: '/static/images/avatar/5.jpg',
//   },
//   {
//     id: 14,
//     primary: 'Summer BBQ',
//     secondary: `Who wants to have a cookout this weekend? I just got some furniture
//       for my backyard and would love to fire up the grill.`,
//     person: '/static/images/avatar/1.jpg',
//   },
// ];

// const StyledFab = styled(Fab)({
//   position: 'absolute',
//   zIndex: 1,
//   top: -30,
//   left: 0,
//   right: 0,
//   margin: '0 auto',
// });

// export default function index() {
//   return (
//     <React.Fragment>
//       <CssBaseline />
//       {/* <Nv/> */}
//       <Paper square sx={{ pb: '50px' }}>
//         <Typography variant="h5" gutterBottom component="div" sx={{ p: 2, pb: 0 }}>
//           Inbox
//         </Typography>
//         <List sx={{ mb: 2 }}>
//           {messages.map(({ id, primary, secondary, person }) => (
//             <React.Fragment key={id}>
//               {id === 1 && (
//                 <ListSubheader sx={{ bgcolor: 'background.paper' }}>
//                   Today
//                 </ListSubheader>
//               )}

//               {id === 3 && (
//                 <ListSubheader sx={{ bgcolor: 'background.paper' }}>
//                   Yesterday
//                 </ListSubheader>
//               )}

//               <ListItem button>
//                 <ListItemAvatar>
//                   <Avatar alt="Profile Picture" src={person} />
//                 </ListItemAvatar>
//                 <ListItemText primary={primary} secondary={secondary} />
//               </ListItem>
//             </React.Fragment>
//           ))}
//         </List>
//       </Paper>
     
//     </React.Fragment>
//   );
// }